import type { Listing } from '../types'

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: '1',
    user_id: '1',
    practice_name: 'Somnus Psychology',
    email: 'info@somnuspsychology.com.au',
    phone: '(03) 6234 5678',
    website: 'https://somnuspsychology.com.au',
    profession: 'Clinical Psychologist',
    practice_type: 'group_practice',
    ahpra_number: 'PSY0001234567',
    specialties: ['Sleep', 'Anxiety', 'Neuromodulation', 'Depression', 'Trauma'],
    location: 'Hobart',
    postcode: '7000',
    street_address: '123 Main Street',
    is_telehealth: true,
    is_rural_outreach: false,
    is_statewide_telehealth: false,
    bio: 'Somnus Psychology supports sleep and emotional wellbeing through CBT-I and individual therapy. The clinic is recognised as a local leader in neuromodulation, offering non invasive tDCS for depression, anxiety and mood based concerns.',
    avatar_url: '/8pa0uv4gu5y-1764918534077.png',
    status: 'approved',
    is_featured: true,
    show_name_publicly: true,
    show_email_publicly: true,
    show_phone_publicly: true,
    show_website_publicly: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: '2',
    practice_name: 'Dr. Sarah Mitchell',
    email: 'sarah.mitchell@example.com',
    phone: '(03) 6234 5678',
    website: 'https://sarahmitchellpsychology.com.au',
    profession: 'Psychologist',
    practice_type: 'individual',
    ahpra_number: 'PSY0002345678',
    specialties: ['Anxiety', 'Depression', 'Trauma', 'CBT'],
    location: 'Hobart',
    postcode: '7000',
    street_address: '456 Collins Street',
    is_telehealth: true,
    is_rural_outreach: false,
    is_statewide_telehealth: false,
    bio: 'Experienced psychologist specializing in anxiety, depression, and trauma-informed care. Offering both in-person and telehealth services.',
    status: 'approved',
    is_featured: false,
    show_name_publicly: true,
    show_email_publicly: true,
    show_phone_publicly: true,
    show_website_publicly: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: '3',
    practice_name: 'Chloe Stone',
    email: 'chloe.stone@example.com',
    phone: '',
    website: '',
    profession: 'Psychologist',
    practice_type: 'individual',
    ahpra_number: 'PSY0003456789',
    specialties: ['Anxiety', 'Depression', 'CBT'],
    location: 'Statewide',
    postcode: '',
    street_address: '',
    is_telehealth: true,
    is_rural_outreach: false,
    is_statewide_telehealth: true,
    bio: 'Experienced psychologist providing compassionate mental health support across Tasmania.',
    status: 'approved',
    is_featured: false,
    show_name_publicly: true,
    show_email_publicly: false,
    show_phone_publicly: false,
    show_website_publicly: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: '4',
    practice_name: 'North West Counselling Practice',
    email: 'admin@nwcounselling.com.au',
    phone: '(03) 6331 2345',
    website: 'https://nwcounselling.com.au',
    profession: 'Counselling Centre',
    practice_type: 'group_practice',
    ahpra_number: '',
    specialties: ['Family Therapy', 'Relationship Issues', 'Grief and Loss'],
    location: 'Launceston',
    postcode: '7250',
    street_address: '789 George Street',
    is_telehealth: false,
    is_rural_outreach: true,
    is_statewide_telehealth: false,
    bio: 'A team of experienced counsellors providing support for individuals, couples, and families across the North West Coast.',
    status: 'approved',
    is_featured: false,
    show_name_publicly: true,
    show_email_publicly: true,
    show_phone_publicly: true,
    show_website_publicly: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
